import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/modules/core/components/NavBar";
import Footer from "@/modules/core/components/Footer";
import ReactQueryProvider from "./providers";
import NavigationBreadcrumbs from "@/modules/core/components/NavigationBreadcrumbs";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-col`}>
        <ReactQueryProvider>
          <header>
            <NavBar />
            <NavigationBreadcrumbs />
          </header>
          <main className="w-full flex-grow flex-1 flex flex-col">
            {children}
          </main>

          <Footer />
        </ReactQueryProvider>
      </body>
    </html>
  );
};

export default RootLayout;
